version: 0.2

phases:
  build:
    commands:
      - echo Build started
      - mvn clean install
      - aws s3 rm --recursive "s3://test2git2bucket/src"
  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - target/order-service.jar
  discard-paths: yes