version: 0.2

phases:
  build:
    commands:
      - echo Build started
      - mvn clean install
      - aws s3 rm s3://test2git2bucket/src/main/java/com/example/EmailSendMime/config/MyConfiguration.java
      - aws s3 cp pom.xml s3://test2git2bucket/src

  post_build:
    commands:
      - echo Build completed Successfully.
artifacts:
  files:
    - target/order-service.jar
  discard-paths: yes