version: 0.2

phases:
  build:
    commands:
      - echo Build started
      - mvn clean install
  post_build:
    commands:
#      - echo Build completed successfully.
      - echo Build completed on 08-02-2023 11:47am
      - mvn package
      - mvn target/wrapper-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - target/order-service.jar
  discard-paths: yes